### ISSUE TITLE
`Get Started` button not visible on GettingStarted screen when screen size is small

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [Anmol92verma/SlackComposeMultiplatform#1]
If the screen/window size is small, then the `Get Started` button becomes invisible due to lack of space thus disabling a user to move forward in screens until he resizes the window as shown in the GIF below.

One of the solutions could be to simply use `Modifier.verticalScroll(rememberScrollState())` to enable scrolling on the screen regardless of its size.

<img src="https://media.giphy.com/media/2OlfrFddFpP23P9q6o/giphy.gif" width="500"/>

**Comment by Anmol92verma** [comment]
@shubhamsinghmutualmobile scrolling is not a recommended solution

**Comment by shubhamsinghmutualmobile** [comment]
@Anmol92verma Okay, then could we fix the `Get Started` button on the `bottomBar` slot in the Scaffold it's being used in and show/hide the button depending upon when it's required?

**Comment by Anmol92verma** [comment]
Ideally the image should be resized accordingly

**Comment by shubhamsinghmutualmobile** [comment]
For that, we'll have to fix the top and bottom content, right? So that the image only uses the space that's provided to it.

**Comment by Anmol92verma** [comment]
Fixed it now
