### ISSUE TITLE
Unable to run the code: Received status code 401 from server

### ISSUE THREAD

**Issue by Aklal** [Anmol92verma/SlackComposeMultiplatform#3]
Hello, 

when importing the project, Android Studio warns for a load error. 
<img width="1092" alt="notes-5183bd0f" src="https://user-images.githubusercontent.com/6785547/191314262-9cc934fb-c393-4030-8365-a3f32f1ccc59.png">

Trying to run the desktop app raises the error `Received status code 401 from server: Unauthorized`:
<img width="2370" alt="Screenshot 2022-09-20 at 18 03 57" src="https://user-images.githubusercontent.com/6785547/191314327-e3e24772-f1b1-4e4b-8ee4-55119d629cac.png">

I try to run the master branch (#9bc0062). Android studio version: Android Studio Dolphin | 2021.3.1.

**Comment by Anmol92verma** [comment]
This repo depends on [An external multiplatform library](https://github.com/Anmol92verma/slackdata)

You can install it in mavenLocal and still use it 👍

**Comment by Aklal** [comment]
Thank for your answer :heart: , it works :thumbsup: :thumbsup:
